--- #YAML:1.0
name:                PPM-Repositories
version:             0.13
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
